### ISSUE TITLE
Project will fail to load on any scratch compiler or scratch.

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower#1]
Hello Im Bloctans just made a Github Account! but...
Basicly I Know that we have to keep the extension private but we should find a way to load the extension without leaking it.'
![image](https://user-images.githubusercontent.com/93960460/140853021-834e61d0-e1bd-4780-8c6f-ba8c90ce374e.png)
(from turbowarp)
![image](https://user-images.githubusercontent.com/93960460/140853026-871db138-698c-4040-9ef3-8d5efb72704f.png)
(from scratch)

**Comment by MikeDev101** [comment]
The source code currently depends on CloudLink. Load the project with CloudLink.

**Comment by Bloctans** [comment]
once again, we have to keep it private. so um how about you make a public version of the extension?

**Comment by Bloctans** [comment]
nvm what i just said.

**Comment by MikeDev101** [comment]
I'm still not sure what you mean by keeping the "extension" private. CloudLink is CloudLink, if you're talking about it.
