### ISSUE TITLE
IP address blocked error

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/Meower#102]
error has happened to both me and @mbrick2
![image](https://user-images.githubusercontent.com/88938765/146093160-11a0ccf6-554a-467b-89c6-e87d63c670f2.png)
![image](https://user-images.githubusercontent.com/88938765/146093400-bfcbfebc-21df-4fcd-8e5c-69b67a56396b.png)

**Comment by MikeDev101** [comment]
Check if the inspection log mentions "failed to fetch IP" or an error for https://api.ipify.org/. CloudLink blocks clients that have a blank IP, and if the meower client fails to get an IP address then it will simply tell the server it has a blank IP.

**Comment by CloudGate1234** [comment]
solved. ublock origin was blocking ipify.org .
