### ISSUE TITLE
Reducing project size

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/Meower#104]
I think it may be possible to use Vadik1's project size reducer on meower
link here: https://xeltalliv.github.io/ScratchTools/ProjectJsonMinimizer/
not that much of a priority and we need to test if it actually will help too.

**Comment by MikeDev101** [comment]
Beta 4.8 was the first build I used this on. It only shrunk it down by a few hundo KB. I don't see this doing much but I suppose it helps.

**Comment by MikeDev101** [comment]
closing as gone stale, I'll try using this tool when publishing new builds from now on
