### ISSUE TITLE
Beta 3 still online

### ISSUE THREAD

**Issue by Samq64** [meower-media-co/Meower#117]
Meower Beta Test 3 is still online at https://MikeDev101.github.io/meower. I'm not sure if this is a problem or not, but either way it should probably be redirected to https://meower.org/Meower or removed.

**Comment by Melt2002** [comment]
It seems to be connecting to a server, although not very well due to it's age. I'll alert MikeDev ASAP.

**Comment by MikeDev101** [comment]
Added a redirect page (or tried to)
