### ISSUE TITLE
date/time fix

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower#20]
from https://scratch.mit.edu/discuss/topic/508318/?page=188#post-5788291

perhaps server-side needs to be logging date/time?

**Comment by Bloctans** [comment]
yeah, but, we will need a script to find the time zone, we could return current(time) block

**Comment by TermOfficial** [comment]
just write "xx:xx EST"

**Comment by TermOfficial** [comment]
or whatever timezone it is

**Comment by MikeDev101** [comment]
Fixed as of latest build, date/time stamps are handled server-side now in the EST timezone
