### ISSUE TITLE
Save User data when servers go down?/disable oobe for the user once done

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower#53]
i had to re make my account (i think)

**Comment by MikeDev101** [comment]
1. OOBE, as well as user settings storage, isn't complete yet. This is a feature NYI (Not Yet Implemented) issue.
2. I was considering an Ad-Hoc Storage mode for the event that the server goes down, but if the primary CloudLink server goes down, everything goes down with it. I'm investigating the issues as to why it periodically crashes.

**Comment by Bloctans** [comment]
maybe run cloudlink in command line and it will spit out an error

**Comment by MikeDev101** [comment]
> maybe run cloudlink in command line and it will spit out an error

I've been running CloudLink on Windows. Most of the time it's a winerror: connection forcibly closed

**Comment by MikeDev101** [comment]
Purely peer-to-peer websockets is not possible at this time, as it requires a server to be present. Closing as this problem with the server going down every 2ish days will be fixed in the next build
