### ISSUE TITLE
Global Chat breaks upon error screen

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower#65]
![image](https://user-images.githubusercontent.com/93960460/143173602-beb90b77-f104-4fef-a26d-74c5fdd0fe50.png)

**Comment by MikeDev101** [comment]
I forgot to add a check to prevent blank posts from being sent, and as for the event of an actual error, I have yet to determine how to hide the chat.

**Comment by MikeDev101** [comment]
Fixed as of latest build
