### ISSUE TITLE
Account approval

### ISSUE THREAD

**Issue by TermOfficial** [meower-media-co/Meower#68]
Some guy just went on meower and decided to spam with (f word)the(n-word)s  as their username. Account approval should be a thing now.
(Repost from scratch)

**Comment by Bloctans** [comment]
wait w h a t

**Comment by Pixelation-Creations** [comment]
urgent. gonna figure out badword/email auth. might need a replit server if we do email auth/acc approval

**Comment by MikeDev101** [comment]
Temporarily disabling password-based authentication to give us some time to get this fixed.

**Comment by MikeDev101** [comment]
Temporary fix pushed as https://github.com/meower-media-co/Meower/commit/89868edd66b69672b1cec0e1a2ecd3cb4554674f

**Comment by Pixelation-Creations** [comment]
almost done with prototype. will post tom or dayafter bc gt sign of now

**Comment by Pixelation-Creations** [comment]
https://scratch.mit.edu/projects/607067214/
it works

**Comment by Pixelation-Creations** [comment]
fixed: https://github.com/Pixelation-Creations/Meower

**Comment by MikeDev101** [comment]
Temporarily locking discussion, awaiting for a consensus in #85

**Comment by MikeDev101** [comment]
Closing as bluelist has been abandoned, and will be using a custom authenticator system
