### ISSUE TITLE
2-Factor Authentication doesn't work if account does not exist

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower#82]
After debugging the issue in #77, we determined the issue of accounts being unable to sign in related to some lack of checks. If an account doesn't exist in the server, and a user tries to authenticate with 2FA, it will throw up a "bool obj not subscriptable" error. 

The workaround, for the time being, is creating a dummy account with a NULLED password. Simply state your scratch username (MUST BE VERBATIM, AS IT IS CASE-SENSITIVE) and I will manually add your account until this issue is fixed.

**Comment by TheWaouh** [comment]
cww2010

**Comment by Rix565** [comment]
Rix56

**Comment by CST1229** [comment]
Possible dirty server workaround for the time being: Try-catch the part that errors and then create an account with a nulled password automatically

**Comment by CST1229** [comment]
Also, CST1229

**Comment by meguy7878** [comment]
meguy7878

**Comment by MikeDev101** [comment]
all added

**Comment by bluepig600** [comment]
bluepig600

**Comment by MikeDev101** [comment]
> bluepig600

already exists

**Comment by Voxalice** [comment]
Voxalice

**Comment by Samq64** [comment]
samq64

**Comment by MikeDev101** [comment]
Added

**Comment by Samq64** [comment]
> Added

I can log in now, but get an internal server error when reaching the home page.

**Comment by MikeDev101** [comment]
> I can log in now, but get an internal server error when reaching the home page.

As of now, I would wait for the server to be upgraded to the latest build of CloudLink.

**Comment by MikeDev101** [comment]
closing as gone stale and will be fixed in next build

**Comment by Touchcreator** [comment]
Touchcreator
