### ISSUE TITLE
Error: server connects, but then disconnects after entering username

### ISSUE THREAD

**Issue by CloudGate1234** [meower-media-co/Meower#89]
![image](https://user-images.githubusercontent.com/88938765/145694772-7651ebf4-dd55-4459-92eb-660d26743edd.png)
The console says that is connected, but then disconnects.

**Comment by MikeDev101** [comment]
We are aware of the issue and it's related to using an older and buggier build of CloudLink. I'm probably going to just make a page for saying that Meower is under development.

**Comment by MikeDev101** [comment]
Fixed (hopefully) as of latest build
