### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower#91]
Connections to the Meower server keep on timing out after about 5 minutes and they cause the client to be disconnected from the server.

**Comment by tnix100** [comment]
This has been happening before 4.7 but I was hoping it was fixed in 4.7, sadly it hasn't been.

**Comment by MikeDev101** [comment]
Sadly a networking issue beyond my understanding, but it might be possible to fix by periodically ping/pong-ing the server. I'll see what I can do.

**Comment by MikeDev101** [comment]
Just ran a quick test. Connection times out after a minute and a half. Perhaps ping/pong the server every 30 seconds?

**Comment by MikeDev101** [comment]
Fixed in minor fix
