### ISSUE TITLE
Account Jamming

### ISSUE THREAD

**Issue by tnix100** [meower-media-co/Meower#92]
Within Meower 4.7 you are still able to account jam. This is done by setting your ID to be the ID of someone else and making it so they're not able to login. This can be fixed by making it so when you successfully authenticate your ID is set by the server and it's set to the username you logged in with.

There should also be a error displayed in Meower if an ID conflict happens, it shouldn't just get frozen at "Please wait...".

**Comment by MikeDev101** [comment]
As mentioned, this is not a vulnerability but more of an annoyance. Will be looking into fixing.

**Comment by MikeDev101** [comment]
Implemented server-side
